### ISSUE TITLE
Coverage of .io Domains

### ISSUE THREAD

**Issue by alixaxel** [rapid7/sonar#1]
I downloaded the forward DNS study and left it running the whole night looking for .io DNS records, unfortunately the script wasn't able to find any.

I suspect that .io domains might not available on this dataset since the IO registrar makes zone access quite painful but since the script didn't finish I'm wondering if you have any sort of statistics available regarding the availability of specific TLDs, .io in concrete?

Thanks

**Comment by jhart-r7** [comment]
Sorry for the delay, @alixaxel.  I can't comment (yet) on `.io` specifically, but perhaps @hmoore-r7 or @mschloesser-r7 have some insight.

With regards to which TLDs we have available, I don't see any reason why we couldn't somehow publish/share that, assuming we aren't already and I just don't know about it.  Let me poke around and see what I can find.

**Comment by hdm** [comment]
The .io NIC doesn't offer zone downloads, but we can predict quite a few using existing domain lists. Leaving this open as a potential TODO for guessing .io names based on other TLDs.

**Comment by alixaxel** [comment]
@hmoore-r7 Yeah, it's a bummer that they don't.

@jhart-r7 No worries about the delay, it would be great if these stats could be shared. :)

**Comment by gwillem** [comment]
@alixaxel FYI I am finding a ton of .io domains in the `20151121_dnsrecords_all.gz` dataset.

**Comment by hdm** [comment]
The ``.io`` TLD doesn't provide zone files, so the only records showing up in the Sonar datasets are those derived from SSL certificates, PTR records, and links within HTML responses.

**Comment by alixaxel** [comment]
@gwillem Thanks for the heads up, I'm gonna have a peek. :)

**Comment by alixaxel** [comment]
@gwillem

I found 284,589 on the latest available dataset but if I count unique domains it goes down to only 27,089.

``` shell
zgrep '[.]io,' ~/20160227_dnsrecords_all.gz | cut -d , -f 1 | rev | cut -d . -f 1-2 | rev | sort -u | wc -l
```

**Comment by jhart-r7** [comment]
Going to close this -- we already get some `.io` domains that show up here via other methods (SSL CNs, HTML links, etc).  The topic of domain/TLD guessing is something we have/are considering.
