### ISSUE TITLE
Why are some IpV4 addresses does not have any DNS info but censys has them 

### ISSUE THREAD

**Issue by harishbsingh** [rapid7/sonar#11]
Example: 52.94.28.30

When I look up this ipAddress in "https://censys.io/", I find that it is actually mapped to "dynamodb.us-west-2.amazonaws.com "

But when I download the file "20170531-rdns.json.gz", I do not find this IpAddress. 

Can you please help/suggest on how to find this info? Also, why do I not find in the downloaded file? 20170531-rdns.json.gz

**Comment by jhart-r7** [comment]
Hello Harish,

The purpose of the Sonar reverse DNS study (https://scans.io/study/sonar.rdns_v2) is to determine the mapping of IP addresses to names by examining the PTR records for the public IPv4 internet space.  In cases where we get no response for the PTR record for a given IP, nothing is stored.    In the case of 52.94.28.30, there does not look to be a currently configured PTR record:

```
$  host 52.94.28.30 4.2.2.1
Using domain server:
Name: 4.2.2.1
Address: 4.2.2.1#53
Aliases: 

Host 30.28.94.52.in-addr.arpa. not found: 3(NXDOMAIN)
```

As such, it won't show up in our study, or at least any runs of this study where a PTR record isn't found. From the looks of things, this IP address hasn't had reverse DNS for at least 90 days.

Knowing the nature of this address space and the domain in question, it is almost definite that things did resolve this way at some point.

On the other hand, if you were to use our forward DNS datasets, https://scans.io/study/sonar.fdns_v2, you'd see that dynamodb.us-west-2.amazonaws.com has resolved to dozens of similar looking IPs in the 52.94.0.0/16 network within the last week.

I hope that answers your question.

Please let us know if there is more we can help clarify.
