### ISSUE TITLE
Missing a big # of names?

### ISSUE THREAD

**Issue by dare05** [rapid7/sonar#12]
A while ago one person opened this thread https://github.com/rapid7/sonar/issues/9

Since then, one of your mods said:

> Among some of the solutions that have been suggested in the past is the requesting of specific record types.

Unfortunately I do not have an estimate for when this will change.

> 

Was this implemented in 2017? Or are you still requesting just ANY queries?

**Comment by jhart-r7** [comment]
Hello @dare05,

We have not yet implemented this in 2017, however there are still a few months left.

Could you explain your use cases for the improved version of the DNS study?  If the ANY study is missing some domains for you, what record types in particular were you hoping to get back?I don't know that we could ever support looking up all record types for all names, but `A`, `MX` and maybe a few other important ones are likely supportable.  Knowing how folks use our data helps inform decisions about what/how we collect that data.

Thanks!

-jon

**Comment by dare05** [comment]
@jhart-r7 I meant more about the domains part, increasing your list of domains. For that, I'd go with a) Trying to get access from all registrars possible that provide zone files (contacting the registry directly or using a tool like wwws [dot] io).

There are also providers providing country-level domain names, but thing is, I've separated the domains from your list and it's bigger than what they provide (except for zone-file [dot] com (click on 'en'), you might want to see what they do because their country-level domain lists are almost 2x bigger than what you have.
