### ISSUE TITLE
Scans.io Not Responding

### ISSUE THREAD

**Issue by naphthalene** [rapid7/sonar#13]
Hi,

I am getting a 404 from https://scans.io/study/sonar.fdns_v2 as of a few hours ago.

Did something change? The archives are still accessible by direct request.

Thanks!

**Comment by naphthalene** [comment]
Its back! ¯\\\_(ツ)\_/¯

**Comment by jhart-r7** [comment]
Good catch, @naphthalene.  The backend of scans.io for each group of studies is a JSON file and one had a syntax error in it that slipped through.  I've addressed the problem and the datasets should be accessible once again.

Out of curiousity, what are you using the FDNS datasets for?

**Comment by naphthalene** [comment]
Hello, I'm reopening this issue - appears https://scans.io is not responding anymore.

**Comment by naphthalene** [comment]
Huh, its back up. Not sure what happened there.

**Comment by jhart-r7** [comment]
Thanks for reporting this.  We also noticed this outage earlier, and it returned on its own.  

For future reference, Rapid7 doesn't manage the scans.io service; we simply use it as a way to distribute the data from Project Sonar.  If you notice future issues with that service, support@censys.io is the best way to get a resolution, however feel free to let us know about the problem as part notifying scans.io.

Thanks!
