### ISSUE TITLE
How do I get Zone files

### ISSUE THREAD

**Issue by chushuai** [rapid7/sonar#14]
Zone files from COM, INFO, ORG, NET, BIZ, INFO and other TLDs
Zone files from gTLDs

**Comment by jhart-r7** [comment]
@chushuai can you clarify what you are asking?  If you are asking if Rapid7's Project Sonar provides zone files for various TLDs, no, currently we do not.  Depending on your use case we may have some data that might work for you.  Please reach out to us at research@rapid7.com and we can discuss further.  If you are asking how to get TLD zone files in general, there are numerous you could use, including https://www.whoisxmlapi.com/newly-registered-domains.php or other sources of newly registered or expired domains.
