### ISSUE TITLE
Malformed 2018-03-28-1522256401-rdns.json.gz

### ISSUE THREAD

**Issue by d33tah** [rapid7/sonar#15]
Take a look at this - I repeated the process twice in order to make sure it's not on my end:

```
ubuntu@ip-172-31-12-201:/mnt/user/1000$ zcat 2018-03-28-1522256401-rdns.json.gz | wc -l
gzip: 2018-03-28-1522256401-rdns.json.gz: invalid compressed data--format violated
748285
```

**Comment by malvidin** [comment]
Did you verify the hash of the downloaded file? I've had that problem before when the file uploaded was corrupted.

If you downloaded the file from Scans.io, check out #16. The RDNS scans recently moved, and attempted downloads currently redirect to Rapid7 page, not the data.

**Comment by jhart-r7** [comment]
Thanks for reporting this.  Where did you download that file from?  https://opendata.rapid7.com/sonar.rdns_v2/2018-03-28-1522256401-rdns.json.gz?

**Comment by d33tah** [comment]
That was before your move to opendata.rapid7.com. Now the file is good.

2018-04-11 19:16 GMT+02:00 Jon Hart <notifications@github.com>:

**Comment by jhart-r7** [comment]
@d33tah I just downloaded https://opendata.rapid7.com/sonar.rdns_v2/2018-03-28-1522256401-rdns.json.gz and confirmed the c02663313b7f5011a250539384bafa23367efbf5 checksum.

**Comment by jhart-r7** [comment]
Ah, thanks @d33tah.  Sorry we missed the initial report of this.  Lately I've been having problems with github notifications not showing up in order, and maybe now I'm also just missing some notifications entirely.

Glad to hear this is resolved.  Please reach out to us if we can help in the future.
