### ISSUE TITLE
scans.io directory is incorrect

### ISSUE THREAD

**Issue by tdsmith** [rapid7/sonar#16]
I don't know if you intend to continue supporting the study metadata at scans.io -- it was very helpful for enumerating available files, but the links are no longer working.

For example, the directory advertises `https://scans.io/data/rapid7/sonar.moressl/20180404/2018-04-04-1522819081-nntps_563_certs.gz`, which redirects to `https://scans.io/_d/data/rapid7/sonar.moressl/20180404/2018-04-04-1522819081-nntps_563_certs.gz`, which redirects to `https://opendata.rapid7.com`, which is of course not a pile of certificates.

Is there a replacement?

**Comment by tdsmith** [comment]
(For clarity, the directory I'm using is `https://scans.io/json`.)

**Comment by jhart-r7** [comment]
Hello @tdsmith,

The redirect chain you are experiencing is expected for now.  We will be hosting the Sonar data on https://opendata.rapid7.com and in the near future all of these files will be available.  As to the metadata, that is something we have discussed and will support in a future iteration.

Thanks!

-jon

**Comment by tdsmith** [comment]
Thanks for the update!

**Comment by jhart-r7** [comment]
I've also spoken with the folks at scans.io and they will be updating the JSON so that it does not list data for studies that are now hosted elsewhere.

**Comment by malvidin** [comment]
How long do you anticipate that this capability gap will exist?

In the mean time, will replacing this:
https://scans.io/data/rapid7/<study.name>/
with this:
https://opendata.rapid7.com/<study.name>/
work with all current Rapid7 datasets?

Subject to current file availability, of course.

**Comment by jhart-r7** [comment]
@malvidin yes.  The path for the datasets relative to the top level has not changed.  And yes, as you point out, this is currently subject to file availability.  

I believe you'll also run into a problem with https://github.com/malvidin/scansio_download if scans.io cleans up scans.io/json such that it no longer lists Rapid7's data.   Feel free to reach out to us at research@rapid7.com and we can discuss this further.

Thanks!

**Comment by jhart-r7** [comment]
@tdsmith you may have noticed, but yesterday scans.io updated the JSON API in such a way that the Rapid7 study files are no longer listed in https://scans.io/json.  An API like this is something we will eventually support.  In the interim, please feel free to reach out to us here or via research@rapid7.com if we can assist with anything.

Thanks!
