### ISSUE TITLE
Please provide a torrent option!

### ISSUE THREAD

**Issue by incidenthunter** [rapid7/sonar#2]
Hello Austin,

Your datasets are awesome, thank you very much for providing them!
Unfortunately, your bandwidth is often limited (from the European point of view). Would it be possible to seed your files on torrent? 

Keep up the good work!

**Comment by jhart-r7** [comment]
Hello,

Thanks for reaching out and sorry for the delay.

Currently, all of the data collected by Rapid7's project sonar is hosted at https://scans.io which is run by the helpful folks at the University of Michigan.  Please reach out to Zakir Dumeric (@zakird) and he can assist you with your question.

Thanks!

-jon
