### ISSUE TITLE
Strategy for web crawling

### ISSUE THREAD

**Issue by gwillem** [rapid7/sonar#5]
Am processing the 20151121_dnsrecords_all.gz dataset as input for a web crawler. It seems to have quite decent coverage, kudo's for that!

I noticed that many (millions) of records are used by companies mapping their entire IP space onto DNS records, such as Softbank (221.32.0.0/11) and therefore, probably not very useful for web crawling.

I optimized by skipping records that have more than 4 digits in any of the non-tld domain tokens, and skipping on `broadband`, `dsl` and `dhcp` but that feels clunky. Anyone else got a better strategy for web crawling?

**Comment by jhart-r7** [comment]
Good question, but a bit outside the scope of sonar.  My only other suggestion might be utilize the [Sonar reverse DNS dataset on scans.io](https://scans.io/study/sonar.rdns).  In many cases -- but definitely not all, so beware -- the reverse DNS for an IPv4 address might map to the "default" name for an IP and therefore something you might want to skip:

```
$  host 221.32.1.1
1.1.32.221.in-addr.arpa domain name pointer softbank221032001001.bbtec.net.
```
