### ISSUE TITLE
Question about content of host files

### ISSUE THREAD

**Issue by weber-gregoire** [rapid7/sonar#8]
Hi,

I have some questions regarding the Rapid7 SSL Certificates files.
I'm currently parsing all the files to get an overview of the certificates and their ip addresses.

The way the files are parsed is the following :
- Order the files from the oldest to the newest
- Parse the cert file, and store each certificate in database
- Parse the host file, and update the certificate in database to add corresponding ips

I noticed that some ip addresses are duplicated on some certificates, wich bring me to ask those two questions :
1. Do the host files contain all the IPs scanned, even if the ip was already scanned before ?
2. Is there a way to know what IP range was scanned for a specific host file, and if so how many files does it take to have the latest full scan ?

Thanks.

**Comment by jhart-r7** [comment]
@weber-gregoire, sorry for the very delayed response here.  Somehow this slipped through the cracks.

Every host file contains every host that was scanned during a given run of that study regardless of whether or not it was scanned in previous runs.   Every run of this study should include the results from every IPv4 address on the public Internet, minus our blacklist, that had 443/TCP open.
