### ISSUE TITLE
Missing 90%+ of DNS Records

### ISSUE THREAD

**Issue by indolering** [rapid7/sonar#9]
You are missing ~[95%](https://www.censys.io/domain/report?q=&field=0.lookup.axfr.support&max_buckets=) of DNS records by relying on -ANY.  You should be requesting individual record types.  Are your config files online somewhere?

**Comment by jhart-r7** [comment]
@indolering, thanks for the report.  This is a known problem.  Among some of the solutions that have been suggested in the past is the requesting of specific record types.  

Unfortunately I do not have an estimate for when this will change.  

Regarding configuration files, no, strictly speaking we don't have anything like this for this study.  Our forward DNS study attempts an ANY query for every name we know about, distributing the lookups across open public DNS servers. 

If you have a more specific question or can share your use-case for this data, perhaps we can give you more detail.

Thanks!

**Comment by indolering** [comment]
> Among some of the solutions that have been suggested in the past is the requesting of specific record types.

There are other optimizations too.

> Regarding configuration files, no, strictly speaking we don't have anything like this for this study.

I might be willing to hack on the problem if you provided source.

> Our forward DNS study attempts an ANY query for every name we know about

Sequentially?  Are you using TCP?

> distributing the lookups across open public DNS servers.

It would be better if you queried authoritative nameservers directly.  How many public resolvers are you using?

> If you have a more specific question or can share your use-case for this data, perhaps we can give you more detail.

For example, I once surveyed ~1/3 of the top million sites for some research on TTL times.  I'm bugging you now because I want to know how large TXT records are in practice.

I can think of a lot of security research:

* Track malware command/control servers.
* Use SPF records to confirm doctored emails.
* Spot malicious actors attempting to performing domain "verification" to get TLS certs.
* Track DNSSEC public keys.

95% is not an exaggeration, you are literally missing all professionally run DNS services because `ANY` requests are used for DDoS attacks and zone walking.  So not only are you missing virtually all of the data, you have a hopelessly biased sample.

**Comment by jhart-r7** [comment]
@indolering, again, thank you for the report.  

Regarding some of your specific questions...

We currently only explicitly perform UDP queries, however in the event that the response is truncated and needs to occur over TCP we will do that.  These queries are performed in parallel by a series of worker nodes that pick off random 100k name batches, choosing 10 random resolvers for each new batch.

Regarding the complications with basing this on `ANY` queries and other/better ways of performing this study, thanks.  Unfortunately, these and other issues/ideas were unknown and not accounted for when this study was created years ago.  Between our own internal research and tickets like this we have identified areas for improvement and hope to see this happen in 2017.

Thanks for describing your use-cases.  Knowing how folks use our data helps inform future studies or changes to existing ones.

**Comment by indolering** [comment]
> We currently only explicitly perform UDP queries, however in the event that the response is truncated and needs to occur over TCP we will do that.

Try falling over to TCP after any error sometime, it might improve your response rates.

> These queries are performed in parallel by a series of worker nodes that pick off random 100k name batches.

Try to ensure that nodes do not perform the same lookup against a given resolver and domain faster than 5 queries/second.

> choosing 10 random resolvers for each new batch.

public-dns.info has a list of ~8K resolvers with 95% uptime.  You *really* should be querying the authoritative nameserver, however.

**Comment by jhart-r7** [comment]
👍 , thanks for the advice.  

We use c-ares/pycares for resolution and I suspect that that error retry you mention isn't enabled by default and is something we'd have to do client-side.  Sounds reasonable but we'd have to weigh the potential increase in responses against any downsides, like longer study times.  

That query rate shouldn't be an issue for us as each name is only ever resolved by one node with 1 retry.  Good to know, though.

We use http://public-dns.info/ for our resolvers already 😄

**Comment by indolering** [comment]
> That query rate shouldn't be an issue for us as each name is only ever resolved by one node with 1 retry.

Are you randomizing the order of names so that subdomains aren't run sequentially?  This is more of a concern if you are hitting the authoritative nameservers directly.

**Comment by jhart-r7** [comment]
Yes, the ordering of the names is random.

**Comment by jhart-r7** [comment]
One bit of detail that I neglected to share in this ticket originally that I recalled when it was raised again in #12, but our study is not just ANY -- it will attempt ANY but if it does not get back an A and AAAA record for that very name, it will do an explicit lookup for the A or AAAA as necessary.  So while we do miss lots of records with ANY, we will scoop some of them back up with the fallback queries.

**Comment by jhart-r7** [comment]
It is also worth noting that since this original ticket was opened we have switched away from using public-dns.info and instead query the authoritative servers directly.  

@indolering if you happen to have a sample of a name that we aren't (or weren't) finding, I'll happily look into why.

**Comment by indolering** [comment]
> it will attempt ANY but if it does not get back an A and AAAA record for that very name, it will do an explicit lookup for the A or AAAA as necessary

So why not add other common record types?
